jobs:
  documentation:
    name: Run terraform-docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: terraform-docs/gh-actions@main
        with:
          git-commit-message: |
            docs: Run terraform-docs
          git-push: "true"
          output-file: README.md
          output-method: inject
          working-dir: .
  release:
    name: Run semantic-release
    needs:
      - documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: git checkout HEAD^
      - run: npm ci
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@18
name: Run release pipeline
on:
  push:
    branches:
      - main
