jobs:
  prettier:
    name: Run prettier
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npx prettier --check .
name: Run prettier
on:
  - pull_request
  - push
